package help.mygod.weixin.dao;

import help.mygod.weixin.entity.SendMessage;
import help.mygod.weixin.entity.SendMessageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SendMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_send_message
     *
     * @mbggenerated Tue Dec 01 17:21:53 CST 2015
     */
    int countByExample(SendMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_send_message
     *
     * @mbggenerated Tue Dec 01 17:21:53 CST 2015
     */
    int deleteByExample(SendMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_send_message
     *
     * @mbggenerated Tue Dec 01 17:21:53 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_send_message
     *
     * @mbggenerated Tue Dec 01 17:21:53 CST 2015
     */
    int insert(SendMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_send_message
     *
     * @mbggenerated Tue Dec 01 17:21:53 CST 2015
     */
    int insertSelective(SendMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_send_message
     *
     * @mbggenerated Tue Dec 01 17:21:53 CST 2015
     */
    List<SendMessage> selectByExample(SendMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_send_message
     *
     * @mbggenerated Tue Dec 01 17:21:53 CST 2015
     */
    SendMessage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_send_message
     *
     * @mbggenerated Tue Dec 01 17:21:53 CST 2015
     */
    int updateByExampleSelective(@Param("record") SendMessage record, @Param("example") SendMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_send_message
     *
     * @mbggenerated Tue Dec 01 17:21:53 CST 2015
     */
    int updateByExample(@Param("record") SendMessage record, @Param("example") SendMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_send_message
     *
     * @mbggenerated Tue Dec 01 17:21:53 CST 2015
     */
    int updateByPrimaryKeySelective(SendMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_send_message
     *
     * @mbggenerated Tue Dec 01 17:21:53 CST 2015
     */
    int updateByPrimaryKey(SendMessage record);
}