package help.mygod.weixin.entity;

public class SendMessage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_send_message.id
     *
     * @mbggenerated Tue Dec 01 17:21:53 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_send_message.enabled
     *
     * @mbggenerated Tue Dec 01 17:21:53 CST 2015
     */
    private Boolean enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_send_message.createtime
     *
     * @mbggenerated Tue Dec 01 17:21:53 CST 2015
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_send_message.msgtype
     *
     * @mbggenerated Tue Dec 01 17:21:53 CST 2015
     */
    private String msgtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_send_message.content
     *
     * @mbggenerated Tue Dec 01 17:21:53 CST 2015
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_send_message.mediaid
     *
     * @mbggenerated Tue Dec 01 17:21:53 CST 2015
     */
    private String mediaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_send_message.thumbmediaid
     *
     * @mbggenerated Tue Dec 01 17:21:53 CST 2015
     */
    private String thumbmediaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_send_message.title
     *
     * @mbggenerated Tue Dec 01 17:21:53 CST 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_send_message.description
     *
     * @mbggenerated Tue Dec 01 17:21:53 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_send_message.musicurl
     *
     * @mbggenerated Tue Dec 01 17:21:53 CST 2015
     */
    private String musicurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_send_message.hqmusicurl
     *
     * @mbggenerated Tue Dec 01 17:21:53 CST 2015
     */
    private String hqmusicurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_send_message.name
     *
     * @mbggenerated Tue Dec 01 17:21:53 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_send_message.keyword
     *
     * @mbggenerated Tue Dec 01 17:21:53 CST 2015
     */
    private String keyword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_send_message.picurl
     *
     * @mbggenerated Tue Dec 01 17:21:53 CST 2015
     */
    private String picurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_send_message.url
     *
     * @mbggenerated Tue Dec 01 17:21:53 CST 2015
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_send_message.id
     *
     * @return the value of t_send_message.id
     *
     * @mbggenerated Tue Dec 01 17:21:53 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_send_message.id
     *
     * @param id the value for t_send_message.id
     *
     * @mbggenerated Tue Dec 01 17:21:53 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_send_message.enabled
     *
     * @return the value of t_send_message.enabled
     *
     * @mbggenerated Tue Dec 01 17:21:53 CST 2015
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_send_message.enabled
     *
     * @param enabled the value for t_send_message.enabled
     *
     * @mbggenerated Tue Dec 01 17:21:53 CST 2015
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_send_message.createtime
     *
     * @return the value of t_send_message.createtime
     *
     * @mbggenerated Tue Dec 01 17:21:53 CST 2015
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_send_message.createtime
     *
     * @param createtime the value for t_send_message.createtime
     *
     * @mbggenerated Tue Dec 01 17:21:53 CST 2015
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_send_message.msgtype
     *
     * @return the value of t_send_message.msgtype
     *
     * @mbggenerated Tue Dec 01 17:21:53 CST 2015
     */
    public String getMsgtype() {
        return msgtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_send_message.msgtype
     *
     * @param msgtype the value for t_send_message.msgtype
     *
     * @mbggenerated Tue Dec 01 17:21:53 CST 2015
     */
    public void setMsgtype(String msgtype) {
        this.msgtype = msgtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_send_message.content
     *
     * @return the value of t_send_message.content
     *
     * @mbggenerated Tue Dec 01 17:21:53 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_send_message.content
     *
     * @param content the value for t_send_message.content
     *
     * @mbggenerated Tue Dec 01 17:21:53 CST 2015
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_send_message.mediaid
     *
     * @return the value of t_send_message.mediaid
     *
     * @mbggenerated Tue Dec 01 17:21:53 CST 2015
     */
    public String getMediaid() {
        return mediaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_send_message.mediaid
     *
     * @param mediaid the value for t_send_message.mediaid
     *
     * @mbggenerated Tue Dec 01 17:21:53 CST 2015
     */
    public void setMediaid(String mediaid) {
        this.mediaid = mediaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_send_message.thumbmediaid
     *
     * @return the value of t_send_message.thumbmediaid
     *
     * @mbggenerated Tue Dec 01 17:21:53 CST 2015
     */
    public String getThumbmediaid() {
        return thumbmediaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_send_message.thumbmediaid
     *
     * @param thumbmediaid the value for t_send_message.thumbmediaid
     *
     * @mbggenerated Tue Dec 01 17:21:53 CST 2015
     */
    public void setThumbmediaid(String thumbmediaid) {
        this.thumbmediaid = thumbmediaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_send_message.title
     *
     * @return the value of t_send_message.title
     *
     * @mbggenerated Tue Dec 01 17:21:53 CST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_send_message.title
     *
     * @param title the value for t_send_message.title
     *
     * @mbggenerated Tue Dec 01 17:21:53 CST 2015
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_send_message.description
     *
     * @return the value of t_send_message.description
     *
     * @mbggenerated Tue Dec 01 17:21:53 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_send_message.description
     *
     * @param description the value for t_send_message.description
     *
     * @mbggenerated Tue Dec 01 17:21:53 CST 2015
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_send_message.musicurl
     *
     * @return the value of t_send_message.musicurl
     *
     * @mbggenerated Tue Dec 01 17:21:53 CST 2015
     */
    public String getMusicurl() {
        return musicurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_send_message.musicurl
     *
     * @param musicurl the value for t_send_message.musicurl
     *
     * @mbggenerated Tue Dec 01 17:21:53 CST 2015
     */
    public void setMusicurl(String musicurl) {
        this.musicurl = musicurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_send_message.hqmusicurl
     *
     * @return the value of t_send_message.hqmusicurl
     *
     * @mbggenerated Tue Dec 01 17:21:53 CST 2015
     */
    public String getHqmusicurl() {
        return hqmusicurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_send_message.hqmusicurl
     *
     * @param hqmusicurl the value for t_send_message.hqmusicurl
     *
     * @mbggenerated Tue Dec 01 17:21:53 CST 2015
     */
    public void setHqmusicurl(String hqmusicurl) {
        this.hqmusicurl = hqmusicurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_send_message.name
     *
     * @return the value of t_send_message.name
     *
     * @mbggenerated Tue Dec 01 17:21:53 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_send_message.name
     *
     * @param name the value for t_send_message.name
     *
     * @mbggenerated Tue Dec 01 17:21:53 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_send_message.keyword
     *
     * @return the value of t_send_message.keyword
     *
     * @mbggenerated Tue Dec 01 17:21:53 CST 2015
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_send_message.keyword
     *
     * @param keyword the value for t_send_message.keyword
     *
     * @mbggenerated Tue Dec 01 17:21:53 CST 2015
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_send_message.picurl
     *
     * @return the value of t_send_message.picurl
     *
     * @mbggenerated Tue Dec 01 17:21:53 CST 2015
     */
    public String getPicurl() {
        return picurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_send_message.picurl
     *
     * @param picurl the value for t_send_message.picurl
     *
     * @mbggenerated Tue Dec 01 17:21:53 CST 2015
     */
    public void setPicurl(String picurl) {
        this.picurl = picurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_send_message.url
     *
     * @return the value of t_send_message.url
     *
     * @mbggenerated Tue Dec 01 17:21:53 CST 2015
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_send_message.url
     *
     * @param url the value for t_send_message.url
     *
     * @mbggenerated Tue Dec 01 17:21:53 CST 2015
     */
    public void setUrl(String url) {
        this.url = url;
    }
}